apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep-3
  namespace: booking
spec:
  selector:
    matchLabels:
      app: hotels-back
  replicas: 1
  #minReadySeconds: 50 #For deployment
  template:
    metadata:
        labels:
          app: hotels-back
    spec:
      containers:
        - name: back-container
          image: 'gcr.io/nazarii-tkachuk-book/github.com/adrianwilczynski4/backendbooking:latest'
          ports:
            - containerPort: 5080

#          resources:
#            limits:
#              memory: "128Mi" #128MB
#              cpu: "200m" #200 milicpu(.2cpu or 20% of the cpu)

          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 2
            httpGet:
                path: /tests
                port: 5080
         # image: 'gcr.io/nazariibooking/github.com/adrianwilczynski4/backendbooking:latest'

          readinessProbe:
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 2
            httpGet:
              path: /tests
              port: 5080